FROM python:3.8-slim


COPY get_my_id.py /app
COPY get_config.py /app
COPY get_logger.py /app
COPY requirements.txt /app

WORKDIR /get_my_id

RUN pip3 install -r requirements.txt

CMD ["python3", "get_my_id.py"]